package io.zumyu.midorin.mapconfig.map;

import org.bukkit.Location;
import org.bukkit.configuration.file.FileConfiguration;
import org.bukkit.configuration.file.YamlConfiguration;
import org.bukkit.plugin.Plugin;

import java.io.File;
import java.io.IOException;
import java.util.*;

public class Map
{
   private File mapFile;
   private String mapName;
   private String worldName;
   private Location worldSpawnPoint;
   private List<String> teams;
   private java.util.Map<String, Location> teamSpawnPoints;

   public Map(File mapFile)
   {
      if (mapFile.exists() & mapFile.getName().endsWith(".yml"))
      {
         this.mapFile = mapFile;
         final FileConfiguration mapFileConfig = YamlConfiguration.loadConfiguration(this.mapFile);

         mapName = mapFileConfig.getString("mapName");
         worldSpawnPoint = (Location) mapFileConfig.get("worldSpawnPoint");
         worldName = worldSpawnPoint.getWorld().getName();
         teams = mapFileConfig.getStringList("team");
         teamSpawnPoints = new HashMap<>();

         for (String team : teams)
         {
            if (mapFileConfig.contains("teamSpawnPoint." + team))
            {
               teamSpawnPoints.put(team, (Location) mapFileConfig.get("teamSpawnPoint." + team));
            }
         }
      }
   }

   /**
    * マップ名取得
    * @return mapName マップ名
    */
   public String getMapName()
   {
      return mapName;
   }

   /**
    * ワールド名取得
    * @return worldName ワールド名
    */
   public String getWorldName()
   {
      return worldName;
   }

   /**
    * 初期スポーン座標取得
    * @return worldSpawnPoint 初期スポーン
    */
   public Location getWorldSpawnPoint()
   {
      return worldSpawnPoint;
   }

   /**
    * チームのリスト取得
    * @return teams チームリスト
    */
   public List<String> getTeams()
   {
      return teams;
   }

   /**
    * チームのスポーン座標取得
    * @param team
    * @return teamSpawnPoint チームが存在していれば、座標を返す。無ければ、null
    */
   public Location getTeamSpawnPoint(String team)
   {
      if (teamSpawnPoints.containsKey(team)) return teamSpawnPoints.get(team);
      return null;
   }

   @Override
   public boolean equals(Object o)
   {
      if (this == o) return true;
      if (o == null || getClass() != o.getClass()) return false;
      Map map = (Map) o;
      return mapFile.equals(map.mapFile) &&
              mapName.equals(map.mapName) &&
              worldName.equals(map.worldName) &&
              worldSpawnPoint.equals(map.worldSpawnPoint) &&
              teams.equals(map.teams) &&
              teamSpawnPoints.equals(map.teamSpawnPoints);
   }

   @Override
   public int hashCode()
   {
      return Objects.hash(mapFile, mapName, worldName, worldSpawnPoint, teams, teamSpawnPoints);
   }

   public static class Editor
   {
      private final Plugin plugin;
      private String mapName;
      private String worldName;
      private Location worldSpawnPoint;
      private final List<String> teams = new ArrayList<>();
      private final java.util.Map<String, Location> teamSpawnPoints = new HashMap<>();

      public Editor(Plugin plugin)
      {
         this.plugin = plugin;
      }

      public void setMapName(String mapName)
      {
         this.mapName = mapName;
      }

      public void setWorldSpawnPoint(Location worldSpawnPoint)
      {
         this.worldSpawnPoint = worldSpawnPoint;
         this.worldName = this.worldSpawnPoint.getWorld().getName();
      }

      public boolean addTeam(String teamName, Location spawnPoint)
      {
         if (!teams.contains(teamName))
         {
            teams.add(teamName);
            teamSpawnPoints.put(teamName, spawnPoint);

            return true;
         }
         else return false;
      }

      public boolean removeTeam(String teamName)
      {
         if (teams.contains(teamName))
         {
            teams.remove(teamName);
            teamSpawnPoints.remove(teamName);

            return true;
         }
         else return false;
      }

      public void create()
      {
         File file = new File(plugin.getDataFolder() + "/map/" + mapName + ".yml");
         FileConfiguration fileConfig = YamlConfiguration.loadConfiguration(file);
         fileConfig.options().header("Do not edit this file.");
         fileConfig.set("mapName", mapName);
         fileConfig.set("worldName", worldName);
         fileConfig.set("worldSpawnPoint", worldSpawnPoint);
         fileConfig.set("team", teams);
         for (String team : teams)
         {
            if (teamSpawnPoints.containsKey(team)) fileConfig.set("teamSpawnPoint." + team, teamSpawnPoints.get(team));
         }

         try
         {
            fileConfig.save(file);
         }
         catch (IOException exception)
         {
            exception.printStackTrace();
         }
      }

      public Plugin getPlugin()
      {
         return plugin;
      }

      public String getMapName()
      {
         return mapName;
      }

      public String getWorldName()
      {
         return worldName;
      }

      public Location getWorldSpawnPoint()
      {
         return worldSpawnPoint;
      }

      public List<String> getTeams()
      {
         return teams;
      }

      public java.util.Map<String, Location> getTeamSpawnPoints()
      {
         return teamSpawnPoints;
      }
   }
}
